a = "howdy, children"
print(a)
a = a.capitalize()
print(a) # make first character in up case
a = a.upper()
print(a)
a = a.casefold()
print(a)
a = a.center(1)
print(a)
c  = a.count("h")
print(c)
byte = a.encode()
print(byte)
bool = a.endswith("n")
print(bool)
a = a.expandtabs(5)
print(a)
f = a.find("d")
print(f)
sharestr = "In phrases '{}' are {} h"
print(sharestr.format(a, c))
a = a.format_map(2)
print(a)
